<a href="https://colab.research.google.com/github/americano-diana/car_class/blob/main/car_classification_redi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Data Loading & Cleaning

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Loading datasets from github raw file

unlabeled_data = pd.read_csv('https://raw.githubusercontent.com/americano-diana/car_class/refs/heads/main/unlabeled_data.csv')
labeled_data = pd.read_csv('https://raw.githubusercontent.com/americano-diana/car_class/refs/heads/main/labeled_data.csv')

In [ ]:
print(unlabeled_data.describe())
print(labeled_data.describe())

                 ID      Adv_year     Adv_month      Reg_year   Runned_Miles  \
count  16130.000000  16130.000000  16130.000000  16130.000000   16130.000000
mean   26918.335586   2006.910601      5.687601   2012.324613   48315.702294
std    15487.095203    142.563826      2.079915      4.593881   40199.379087
min        1.000000    202.000000      1.000000   1970.000000  -19585.000000
25%    13595.500000   2018.000000      4.000000   2009.000000   15579.000000
50%    26997.000000   2018.000000      5.000000   2013.000000   39555.000000
75%    40298.750000   2018.000000      7.000000   2016.000000   74432.250000
max    53760.000000   2021.000000     12.000000   2019.000000  880000.000000

              Price      Seat_num      Door_num      issue_id       Adv_day  \
count  1.613000e+04  16130.000000  16130.000000  16130.000000  16130.000000
mean   1.222558e+04      5.085121      4.348977      0.497768     14.481401
std    3.562358e+04      1.546119      1.112513      1.131461      8.071887
min    1.000000e+02      2.000000      0.000000      0.000000      1.000000
25%    3.571250e+03      5.000000      3.000000      0.000000      8.000000
50%    7.295000e+03      5.000000      5.000000      0.000000     14.000000
75%    1.189900e+04      5.000000      5.000000      0.000000     21.000000
max    2.200000e+06     20.000000      6.000000      5.000000     28.000000

       repair_complexity
count       16130.000000
mean            1.283881
std             0.550568
min             1.000000
25%             1.000000
50%             1.000000
75%             1.000000
max             4.000000
                 ID      Adv_year     Adv_month      Reg_year   Runned_Miles  \
count  37636.000000  37636.000000  37636.000000  37636.000000   37636.000000
mean   26868.570199   2006.104900      5.682352   2012.382639   48194.858752
std    15535.763496    147.533118      2.072882      4.567317   39475.087212
min        2.000000    202.000000      1.000000   1960.000000  -19826.000000
25%    13373.500000   2018.000000      4.000000   2009.000000   15389.750000
50%    26832.000000   2018.000000      5.000000   2013.000000   39249.000000
75%    40341.750000   2018.000000      7.000000   2016.000000   74204.500000
max    53766.000000   2021.000000     13.000000   2019.000000  900000.000000

              Price      Seat_num      Door_num      issue_id       Adv_day  \
count  3.763600e+04  37636.000000  37636.000000  37636.000000  37636.000000
mean   1.184000e+04      5.114040      4.345653      0.499681     14.485997
std    3.404482e+04      1.640498      1.115353      1.133672      8.089406
min    1.250000e+02      2.000000      0.000000      0.000000      1.000000
25%    3.500000e+03      5.000000      3.000000      0.000000      7.000000
50%    7.343500e+03      5.000000      5.000000      0.000000     14.000000
75%    1.199000e+04      5.000000      5.000000      0.000000     22.000000
max    2.599990e+06     20.000000      7.000000      5.000000     28.000000

       repair_complexity         Label
count       37636.000000  37636.000000
mean            1.281566      0.109868
std             0.545602      0.312730
min             1.000000      0.000000
25%             1.000000      0.000000
50%             1.000000      0.000000
75%             1.000000      0.000000
max             4.000000      1.000000

In [ ]:
#Check missing values in labeled df
col_nans = labeled_data.isnull().sum()
print(f"Nan values per column: \n{col_nans}")

total_nans = labeled_data.isnull().sum().sum()
print(f"Total nans in labeled_data are: {total_nans}")

Nan values per column:
ID                   0
Maker                0
Genmodel             0
Genmodel_ID          0
Adv_year             0
Adv_month            0
Color                0
Reg_year             0
Bodytype             0
Runned_Miles         0
Engin_size           0
Gearbox              0
Fuel_type            0
Price                0
Seat_num             0
Door_num             0
issue                0
issue_id             0
Adv_day              0
breakdown_date       0
repair_complexity    0
repair_cost          0
repair_hours         0
repair_date          0
value                0
Label                0
dtype: int64
Total nans in labeled_data are: 0

In [ ]:
#Check missing values in unlabeled df
col_nans = unlabeled_data.isnull().sum()
print(f"Nan values per column: \n{col_nans}")

total_nans = unlabeled_data.isnull().sum().sum()
print(f"Total nans in unlabeled_data are: {total_nans}")

Nan values per column:
ID                   0
Maker                0
Genmodel             0
Genmodel_ID          0
Adv_year             0
Adv_month            0
Color                0
Reg_year             0
Bodytype             0
Runned_Miles         0
Engin_size           0
Gearbox              0
Fuel_type            0
Price                0
Seat_num             0
Door_num             0
issue                0
issue_id             0
Adv_day              0
breakdown_date       0
repair_complexity    0
repair_cost          0
repair_hours         0
repair_date          1
value                0
dtype: int64
Total nans in unlabeled_data are: 1

In [ ]:
unlabeled_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16130 entries, 0 to 16129
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 16130 non-null  int64
 1   Maker              16130 non-null  object
 2   Genmodel           16130 non-null  object
 3   Genmodel_ID        16130 non-null  object
 4   Adv_year           16130 non-null  int64
 5   Adv_month          16130 non-null  int64
 6   Color              16130 non-null  object
 7   Reg_year           16130 non-null  float64
 8   Bodytype           16130 non-null  object
 9   Runned_Miles       16130 non-null  int64
 10  Engin_size         16130 non-null  object
 11  Gearbox            16130 non-null  object
 12  Fuel_type          16130 non-null  object
 13  Price              16130 non-null  float64
 14  Seat_num           16130 non-null  float64
 15  Door_num           16130 non-null  float64
 16  issue              16130 non-null  object
 17  issue_id           16130 non-null  int64
 18  Adv_day            16130 non-null  int64
 19  breakdown_date     16130 non-null  object
 20  repair_complexity  16130 non-null  int64
 21  repair_cost        16130 non-null  object
 22  repair_hours       16130 non-null  object
 23  repair_date        16129 non-null  object
 24  value              16130 non-null  object
dtypes: float64(4), int64(7), object(14)
memory usage: 3.1+ MB

In [ ]:
labeled_data.columns

Index(['ID', 'Maker', 'Genmodel', 'Genmodel_ID', 'Adv_year', 'Adv_month',
       'Color', 'Reg_year', 'Bodytype', 'Runned_Miles', 'Engin_size',
       'Gearbox', 'Fuel_type', 'Price', 'Seat_num', 'Door_num', 'issue',
       'issue_id', 'Adv_day', 'breakdown_date', 'repair_complexity',
       'repair_cost', 'repair_hours', 'repair_date', 'value', 'Label'],
      dtype='object')

In [ ]:
labeled_data.dtypes

ID                     int64
Maker                 object
Genmodel              object
Genmodel_ID           object
Adv_year               int64
Adv_month              int64
Color                 object
Reg_year             float64
Bodytype              object
Runned_Miles           int64
Engin_size            object
Gearbox               object
Fuel_type             object
Price                float64
Seat_num             float64
Door_num             float64
issue                 object
issue_id               int64
Adv_day                int64
breakdown_date        object
repair_complexity      int64
repair_cost           object
repair_hours          object
repair_date           object
value                 object
Label                  int64
dtype: object

In [ ]:
labeled_data.head(30)

,ID,Maker,Genmodel,Genmodel_ID,Adv_year,Adv_month,Color,Reg_year,Bodytype,Runned_Miles,...,issue,issue_id,Adv_day,breakdown_date,repair_complexity,repair_cost,repair_hours,repair_date,value,Label
0,11224,Chevrolet,Matiz,16_12,2018,8,Silver,2008.0,Hatchback,61200,...,Excessive Emissions,0,7,2018-08-07,1,206.291,1.0,2018-08-07,664.756.621.144.312,0
1,13673,Ford,Kuga,29_25,2018,5,White,2015.0,SUV,36579,...,Radiator Leaking,0,9,2018-05-09,1,283.82,2.0,2018-05-09,1.158.184.404.071.750,0
2,9528,Ford,Fiesta,29_13,2018,7,Red,2010.0,Hatchback,71000,...,Engine Issue,3,14,2018-07-14,1,500.0,12.0,2018-07-17,246.909.489.589.162,0
3,40424,DS,3,21_1,2018,3,Black,2017.0,Hatchback,6449,...,Flat Tyres,0,25,2018-03-25,2,440.374,2.0,2018-03-25,12.785.925.743.662.900,0
4,10711,Ford,S-Max,29_31,2018,5,White,2014.0,MPV,63751,...,Windscreen Crack,0,14,2018-05-14,1,270.794,1.0,2018-05-14,11.203.607.998.761.700,0
5,27046,Ford,Focus,29_14,2018,8,Orange,2005.0,Hatchback,98452,...,Transmission Issue,2,6,2018-08-06,1,34.566.735.171.940.400,3.0,2018-08-06,37.971.606.018.346.000,1
6,19237,Citroen,SpaceTourer,18_27,2017,9,Orange,2017.0,MPV,1333,...,Alternator Failing,0,4,2017-09-04,2,499.8,4.0,2017-09-05,19.950.267.440.712.500,0
7,2102,Ford,Fiesta,29_13,2018,7,Blue,2008.0,Hatchback,105000,...,Brake Pads Worn,0,27,2018-07-27,1,40.8,2.0,2018-07-27,15.207.396.032.215.700,0
8,1443,Ford,Kuga,29_25,2018,8,Grey,2014.0,SUV,44000,...,Alternator Failing,0,4,2018-08-04,1,259.9,2.0,2018-08-04,1.045.061.097.537.710,0
9,19127,Fiat,500,28_2,2018,6,Red,2015.0,Hatchback,25000,...,Engine Issue,4,12,2018-06-12,1,534.95,10.0,2018-06-14,6.362.668.562.243.350,0
10,5904,Citroen,C4 Cactus,18_13,2021,4,Black,2019.0,Hatchback,5559,...,Excessive Emissions,0,18,2021-04-18,2,518.575,2.0,2021-04-18,12.527.279.107.650.600,0
11,24057,Citroen,C3,18_8,2018,7,Grey,2017.0,Hatchback,14798,...,Flat Tyres,0,19,2018-07-19,2,426.541,2.0,2018-07-19,8.394.882.437.810.860,0
12,39145,Fiat,500,28_2,2018,6,Blue,2017.0,Hatchback,13000,...,Flat Tyres,0,8,2018-06-08,1,22.385,1.0,2018-06-08,7.551.693.303.784.150,0
13,27768,Ford,Fiesta,29_13,2018,5,Blue,2007.0,Hatchback,25000,...,Tyre Alignment,0,5,2018-05-05,1,10.3695,0.5,2018-05-05,35.074.694.371.604.300,0
14,19460,Fiat,Bravo,28_10,2018,7,Red,2007.0,Hatchback,54000,...,Excessive Emissions,0,19,2018-07-19,1,218.855,1.0,2018-07-19,19.835.176.440.589.300,0
15,10864,Ford,Fusion,29_18,2018,4,Silver,2008.0,Hatchback,47032,...,Excessive Emissions,0,5,2018-04-05,1,23.6,1.0,2018-04-05,3.810.088.037.886.370,0
16,15716,Honda,CR-V,34_3,2018,8,Black,2011.0,SUV,81733,...,Windscreen Crack,0,12,2018-08-12,1,25.154,1.0,2018-08-12,81.633.637.349.097.900,0
17,44797,Ford,Mondeo,29_27,2018,5,Green,2007.0,Hatchback,103000,...,Steering Wheel Shaking,0,21,2018-05-21,1,21.295,1.0,2018-05-21,12.275.941.326.318.600,0
18,50704,Citroen,C4,18_12,2018,9,Red,2013.0,Hatchback,42309,...,Radiator Leaking,0,19,2018-09-19,2,184.82,4.0,2018-09-20,4.980.493.640.053.810,0
19,13978,Honda,Accord,34_1,2018,8,Gelb,2009.0,Estate,93000,...,Windscreen Crack,0,12,2018-08-12,1,23.297,1.0,2018-08-12,5.219.772.276.484.520,1
20,40080,Fiat,500,28_2,2018,8,Grey,2014.0,Hatchback,38209,...,Steering Wheel Shaking,0,22,2018-08-22,1,24.8,1.0,2018-08-22,4.559.903.257.881.240,0
21,25353,Ford,Focus,29_14,2017,1,Orange,2010.0,Hatchback,111300,...,Alternator Failing,0,13,2017-01-13,1,182.9,2.0,2017-01-13,6.791.596.543.949.970,0
22,14738,Ford,Focus,29_14,2018,5,Gelb,2004.0,Hatchback,56000,...,Transmission Issue,3,12,2018-05-12,1,-168.991,8.0,2018-05-14,9.530.948.044.922.500,1
23,19116,Ford,Ranger,29_30,2018,7,Grey,2004.0,Pickup,85000,...,Gear Box Issue,0,20,2018-07-20,1,-48.535.646.714.965.600,2.0,2018-07-20,4.277.213.678.701.890,1
24,2998,Ford,Fiesta,29_13,2018,4,Black,2014.0,Hatchback,40036,...,Windscreen Crack,0,15,2018-04-15,1,26.15,1.0,2018-04-15,9.739.535.258.143.120,0
25,4387,Ford,Fiesta,29_13,2018,3,Black,2012.0,Hatchback,38977,...,Steering Wheel Shaking,0,22,2018-03-22,1,29.799,1.0,2018-03-22,930.801.893.610.517,0
26,40349,Dacia,Sandero Stepway,22_4,2018,7,White,2016.0,Hatchback,22000,...,Starter Motor Issue,0,26,2018-07-26,1,-127.5,3.0,2018-07-26,641.891.914.970.406,0
27,39780,Citroen,C4 Cactus,18_13,2018,4,Purple,2018.0,Hatchback,10,...,Engine Issue,1,21,2018-04-21,2,2499.0,16.0,2018-04-25,10.354.865.730.339.500,0
28,53687,Ford,Fusion,29_18,2018,4,Grey,2007.0,Hatchback,73000,...,Engine Issue,1,22,2018-04-22,1,460.0,8.0,2018-04-24,14.183.957.560.924.800,0
29,38826,Bentley,Continental,10_5,2021,6,Black,2019.0,Convertible,6705,...,Tyre Alignment,0,10,2021-06-10,3,509.895,1.5,2021-06-10,19.940.236.157.942.600,0

In [ ]:
#Got to do some cleaning up, let's rename some columns and variables

clean_labeled = labeled_data.copy()

clean_labeled['Fuel_type'] = clean_labeled['Fuel_type'].replace('still_Diesel_but_you_found_an_easteregg', 'Diesel')
clean_labeled.rename(columns={'Engin_size': 'Engine_size'}, inplace=True)
clean_labeled['Engine_size'] = clean_labeled['Engine_size'].str.replace('L$', '', regex=True).astype(float)
clean_labeled['Genmodel_ID'] = clean_labeled['Genmodel_ID'].str.replace('_', '.').astype(float)

In [ ]:
clean_unlabeled = unlabeled_data.copy()

clean_unlabeled['Fuel_type'] = clean_unlabeled['Fuel_type'].replace('still_Diesel_but_you_found_an_easteregg', 'Diesel')
clean_unlabeled.rename(columns={'Engin_size': 'Engine_size'}, inplace=True)
clean_unlabeled['Engine_size'] = clean_unlabeled['Engine_size'].str.replace('L$', '', regex=True).astype(float)
clean_unlabeled['Genmodel_ID'] = clean_unlabeled['Genmodel_ID'].str.replace('_', '.').astype(float)

In [ ]:
print(clean_labeled["Engine_size"].unique())

[1.00e+00 2.00e+00 1.25e+00 1.20e+00 2.50e+00 1.60e+00 1.40e+00 2.20e+00
 9.00e-01 6.00e+00 1.30e+00 1.50e+00 4.30e+00 1.80e+00 6.20e+00 1.10e+00
 1.90e+00 5.00e+00 5.50e+00 2.80e+00 4.00e+00 3.20e+00 9.99e+02 4.50e+00
 2.30e+00 2.40e+00 8.00e-01 3.90e+00 6.30e+00 3.00e+00 3.60e+00 1.70e+00
 4.70e+00 3.30e+00 5.70e+00 6.50e+00 3.70e+00 6.75e+00 2.70e+00 6.80e+00
 3.50e+00 5.20e+00 6.60e-01 2.90e+00 5.30e+00 6.70e+00 6.40e+00 6.10e+00
 5.40e+00 7.00e+00 3.80e+00 4.60e+00 5.80e+00 4.20e+00]

In [ ]:
clean_labeled.head()

,ID,Maker,Genmodel,Genmodel_ID,Adv_year,Adv_month,Color,Reg_year,Bodytype,Runned_Miles,...,issue,issue_id,Adv_day,breakdown_date,repair_complexity,repair_cost,repair_hours,repair_date,value,Label
0,11224,Chevrolet,Matiz,16.12,2018,8,Silver,2008.0,Hatchback,61200,...,Excessive Emissions,0,7,2018-08-07,1,206.291,1.0,2018-08-07,664.756.621.144.312,0
1,13673,Ford,Kuga,29.25,2018,5,White,2015.0,SUV,36579,...,Radiator Leaking,0,9,2018-05-09,1,283.82,2.0,2018-05-09,1.158.184.404.071.750,0
2,9528,Ford,Fiesta,29.13,2018,7,Red,2010.0,Hatchback,71000,...,Engine Issue,3,14,2018-07-14,1,500.0,12.0,2018-07-17,246.909.489.589.162,0
3,40424,DS,3,21.10,2018,3,Black,2017.0,Hatchback,6449,...,Flat Tyres,0,25,2018-03-25,2,440.374,2.0,2018-03-25,12.785.925.743.662.900,0
4,10711,Ford,S-Max,29.31,2018,5,White,2014.0,MPV,63751,...,Windscreen Crack,0,14,2018-05-14,1,270.794,1.0,2018-05-14,11.203.607.998.761.700,0

In [ ]:
#Value column seems to be incredibly high, let's drop it

clean_labeled.drop("value", axis=1, inplace=True)
clean_unlabeled.drop("value", axis=1, inplace=True)

In [ ]:
#Let's change cost and hours to nunmerical

clean_labeled['repair_hours'] = pd.to_numeric(clean_labeled['repair_hours'], errors='coerce')
clean_labeled['repair_cost'] = pd.to_numeric(clean_labeled['repair_cost'], errors='coerce')

In [ ]:
clean_unlabeled['repair_hours'] = pd.to_numeric(clean_unlabeled['repair_hours'], errors='coerce')
clean_unlabeled['repair_cost'] = pd.to_numeric(clean_unlabeled['repair_cost'], errors='coerce')

In [ ]:
clean_unlabeled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16130 entries, 0 to 16129
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 16130 non-null  int64
 1   Maker              16130 non-null  object
 2   Genmodel           16130 non-null  object
 3   Genmodel_ID        16130 non-null  float64
 4   Adv_year           16130 non-null  int64
 5   Adv_month          16130 non-null  int64
 6   Color              16130 non-null  object
 7   Reg_year           16130 non-null  float64
 8   Bodytype           16130 non-null  object
 9   Runned_Miles       16130 non-null  int64
 10  Engine_size        16130 non-null  float64
 11  Gearbox            16130 non-null  object
 12  Fuel_type          16130 non-null  object
 13  Price              16130 non-null  float64
 14  Seat_num           16130 non-null  float64
 15  Door_num           16130 non-null  float64
 16  issue              16130 non-null  object
 17  issue_id           16130 non-null  int64
 18  Adv_day            16130 non-null  int64
 19  breakdown_date     16130 non-null  object
 20  repair_complexity  16130 non-null  int64
 21  repair_cost        13994 non-null  float64
 22  repair_hours       15329 non-null  float64
 23  repair_date        16129 non-null  object
dtypes: float64(8), int64(7), object(9)
memory usage: 3.0+ MB

In [ ]:
# Let's remove Genmodel as we have Genmodel_ID. Breakdown date and repair date can be transformed into repair_days, especially as we remove outliers

In [ ]:
clean_labeled.drop(["Genmodel", "breakdown_date","repair_date"], axis=1, inplace=True)
clean_unlabeled.drop(["Genmodel", "breakdown_date","repair_date"], axis=1, inplace=True)

In [ ]:
# Negative values for runned_miles and repair_cost might be typos, let's turn them into positive numbers

clean_labeled['Runned_Miles'] = clean_labeled['Runned_Miles'].abs()
clean_labeled['repair_cost'] = clean_labeled['repair_cost'].abs()

In [ ]:
clean_labeled.describe()

,ID,Genmodel_ID,Adv_year,Adv_month,Reg_year,Runned_Miles,Engine_size,Price,Seat_num,Door_num,issue_id,Adv_day,repair_complexity,repair_cost,repair_hours,Label
count,37636.000000,37636.000000,37636.000000,37636.000000,37636.000000,37636.000000,37636.000000,3.763600e+04,37636.000000,37636.000000,37636.000000,37636.000000,37636.000000,32582.000000,35749.000000,37636.000000
mean,26868.570199,26.619578,2006.104900,5.682352,2012.382639,48264.431555,3.638479,1.184000e+04,5.114040,4.345653,0.499681,14.485997,1.281566,319.512538,3.917620,0.109868
std,15535.763496,5.747058,147.533118,2.072882,4.567317,39389.990974,43.887572,3.404482e+04,1.640498,1.115353,1.133672,8.089406,0.545602,1029.728706,4.776841,0.312730
min,2.000000,2.100000,202.000000,1.000000,1960.000000,0.000000,0.660000,1.250000e+02,2.000000,0.000000,0.000000,1.000000,1.000000,10.020000,0.500000,0.000000
25%,13373.500000,22.300000,2018.000000,4.000000,2009.000000,15431.500000,1.250000,3.500000e+03,5.000000,3.000000,0.000000,7.000000,1.000000,44.995000,1.000000,0.000000
50%,26832.000000,29.130000,2018.000000,5.000000,2013.000000,39249.000000,1.600000,7.343500e+03,5.000000,5.000000,0.000000,14.000000,1.000000,154.950000,2.000000,0.000000
75%,40341.750000,29.250000,2018.000000,7.000000,2016.000000,74204.500000,2.000000,1.199000e+04,5.000000,5.000000,0.000000,22.000000,1.000000,292.830500,4.000000,0.000000
max,53766.000000,36.100000,2021.000000,13.000000,2019.000000,900000.000000,999.000000,2.599990e+06,20.000000,7.000000,5.000000,28.000000,4.000000,52119.800000,64.000000,1.000000

# Finding and removing outliers

In [ ]:
outlier_cols = ["Adv_year", "Runned_Miles", "Engine_size", "repair_cost"]

In [ ]:
#Identify outliers using IQR

def get_outliers_iqr(df, col):
    Q1 = df[col].quantile(0.01)
    Q3 = df[col].quantile(0.99)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    return outliers

for col in outlier_cols:
    outliers = get_outliers_iqr(clean_labeled, col)
    print(f"\nOutliers in '{col}': {len(outliers)} rows")
    display(outliers[[col]].sort_values(by=col))

Outliers in 'Adv_year': 250 rows

       Adv_year
287         202
336         202
357         202
420         202
465         202
...         ...
36579       202
36640       202
36704       202
37219       202
37355       202

[250 rows x 1 columns]

Outliers in 'Runned_Miles': 4 rows

       Runned_Miles
27246        635000
24881        640000
15470        780000
30956        900000

Outliers in 'Engine_size': 73 rows

       Engine_size
403          999.0
801          999.0
1831         999.0
2315         999.0
2533         999.0
...            ...
33306        999.0
34244        999.0
35617        999.0
36711        999.0
36887        999.0

[73 rows x 1 columns]

Outliers in 'repair_cost': 83 rows

       repair_cost
15139      7419.00
13613      7422.50
30090      7427.50
20077      7579.75
4637       7677.50
...            ...
29674     36479.00
30387     42457.80
33881     44470.00
17640     44470.00
5582      52119.80

[83 rows x 1 columns]

In [ ]:
# Drop outliers & transform typos

#Engine size is often labeled 999c, 999L is likely a typo
clean_labeled.loc[clean_labeled['Engine_size'] == 999, 'Engine_size'] = 0.9

#Adv year = 202 is likely a typo and likely to be 2020 however this is unsure, so best to remove these
clean_labeled = clean_labeled[clean_labeled['Adv_year'] != 202]

In [ ]:
#Engine size is often labeled 999c, 999L is likely a typo
clean_unlabeled.loc[clean_unlabeled['Engine_size'] == 999, 'Engine_size'] = 0.9

In [ ]:
#Remove outliers for repair cost and runned miles which have a very high STD
def remove_outliers_iqr(df, col):
    Q1 = df[col].quantile(0.05)
    Q3 = df[col].quantile(0.95)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Remove outliers from 'repair_cost'
clean_labeled = remove_outliers_iqr(clean_labeled, 'repair_cost')

# Remove outliers from 'runned_miles'
clean_labeled = remove_outliers_iqr(clean_labeled, 'Runned_Miles')

In [ ]:
# Quick summary after cleaning
clean_labeled.head()

,ID,Maker,Genmodel_ID,Adv_year,Adv_month,Color,Reg_year,Bodytype,Runned_Miles,Engine_size,...,Price,Seat_num,Door_num,issue,issue_id,Adv_day,repair_complexity,repair_cost,repair_hours,Label
0,11224,Chevrolet,16.12,2018,8,Silver,2008.0,Hatchback,61200,1.00,...,699.0,5.0,5.0,Excessive Emissions,0,7,1,206.291,1.0,0
1,13673,Ford,29.25,2018,5,White,2015.0,SUV,36579,2.00,...,12191.0,5.0,5.0,Radiator Leaking,0,9,1,283.820,2.0,0
2,9528,Ford,29.13,2018,7,Red,2010.0,Hatchback,71000,1.25,...,2600.0,5.0,3.0,Engine Issue,3,14,1,500.000,12.0,0
3,40424,DS,21.10,2018,3,Black,2017.0,Hatchback,6449,1.20,...,13458.0,5.0,3.0,Flat Tyres,0,25,2,440.374,2.0,0
4,10711,Ford,29.31,2018,5,White,2014.0,MPV,63751,2.00,...,11799.0,7.0,5.0,Windscreen Crack,0,14,1,270.794,1.0,0

In [ ]:
clean_unlabeled.head()

,ID,Maker,Genmodel_ID,Adv_year,Adv_month,Color,Reg_year,Bodytype,Runned_Miles,Engine_size,...,Fuel_type,Price,Seat_num,Door_num,issue,issue_id,Adv_day,repair_complexity,repair_cost,repair_hours
0,29455,Ford,29.25,2018,4,Green,2015.0,SUV,34000,2.0,...,Diesel,17290.0,5.0,5.0,Starter Motor Issue,0,15,1,232.900,3.0
1,41446,Fiat,28.20,2018,8,White,2009.0,Hatchback,65000,1.2,...,Petrol,3980.0,4.0,3.0,Warning Light,0,6,1,219.800,9.0
2,42116,Fiat,28.20,2018,4,Black,2012.0,Hatchback,54491,1.2,...,Petrol,4495.0,4.0,3.0,Flat Tyres,0,24,1,213.485,1.0
3,32619,Citroen,21.30,2018,7,Silver,2011.0,Hatchback,98000,1.6,...,Diesel,4795.0,5.0,5.0,Starter Motor Issue,0,12,2,167.950,6.0
4,51078,Abarth,2.40,2018,6,Red,2014.0,Hatchback,49583,1.4,...,Petrol,11000.0,4.0,3.0,Brake Pads Worn,0,20,2,85.500,4.0

Clean labeled is now ready for being used for modelling

In [ ]:
model_data = clean_labeled.copy()

In [ ]:
test_data = clean_unlabeled.copy()

In [ ]:
model_data.to_csv('model_data.csv', index=False)
test_data.to_csv('unlabeled_clean.csv', index=False)

from google.colab import files
files.download('model_data.csv')
files.download('unlabeled_clean.csv')

# Modeling with XGBoost

In [ ]:
from sklearn.preprocessing import LabelEncoder

cat_cols = model_data.select_dtypes(include='object').columns

for col in cat_cols:
    le = LabelEncoder()
    model_data[col] = le.fit_transform(model_data[col].astype(str))

In [ ]:
from sklearn.model_selection import train_test_split

X = model_data.drop(columns=['Label'])
y = model_data['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
import xgboost as xgb

scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

model = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42,
    scale_pos_weight=scale_pos_weight
)

model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:46:24] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9530075187969925

Confusion Matrix:
 [[5771  238]
 [  62  313]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.96      0.97      6009
           1       0.57      0.83      0.68       375

    accuracy                           0.95      6384
   macro avg       0.78      0.90      0.83      6384
weighted avg       0.96      0.95      0.96      6384

Results are good for predicting label 0 but not for label 1!

In [ ]:
#Let's try to do parameter tuning and see if model behaves better

from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [1, 3, 5],
    'learning_rate': [0.1, 0.2],
    'n_estimators': [100, 200, 300]
}

xgb_clf = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42,
    scale_pos_weight = scale_pos_weight
)

grid_search = GridSearchCV(
    estimator=xgb_clf,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    verbose=1,
    n_jobs=-1
)

grid_search.fit(X, y)

# Get best params
print("Best parameters found: ", grid_search.best_params_)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:13] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Best parameters found:  {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 300}

In [ ]:
#Let's retrain a final model with the best params

best_params = grid_search.best_params_

# Re-train model
final_model = xgb.XGBClassifier(
    **best_params,
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42,
    scale_pos_weight = scale_pos_weight
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Final model
final_model.fit(X_train, y_train)

# Evaluate
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = final_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:14] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Accuracy: 0.9500313283208021

Confusion Matrix:
 [[5735  299]
 [  20  330]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.95      0.97      6034
           1       0.52      0.94      0.67       350

    accuracy                           0.95      6384
   macro avg       0.76      0.95      0.82      6384
weighted avg       0.97      0.95      0.96      6384

In [ ]:
#Now let's try kfold validation

from sklearn.model_selection import cross_val_score, KFold
import numpy as np

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Run cross-validation
cv_scores = cross_val_score(final_model, X, y, cv=kfold, scoring='accuracy')

# Results
print("Cross-validation accuracy scores:", cv_scores)
print("Mean CV accuracy:", np.mean(cv_scores))
print("Standard Deviation:", np.std(cv_scores))

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:15] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:16] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:17] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:18] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:47:19] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Cross-validation accuracy scores: [0.95065789 0.95347744 0.95504386 0.9533208  0.95410401]
Mean CV accuracy: 0.9533208020050126
Standard Deviation: 0.001462734026306855

In [ ]:
# Model looks alright now let's try predicting labels for test data (unlabeled)

In [ ]:
# Need to encode test_data too for XGBoost model

cat_cols = test_data.select_dtypes(include='object').columns

for col in cat_cols:
    le = LabelEncoder()
    test_data[col] = le.fit_transform(test_data[col].astype(str))

In [ ]:
# Predict labels
predicted_labels = final_model.predict(test_data)

# Add predictions to the DataFrame
test_data['Label'] = predicted_labels

In [ ]:
final_predictions = test_data[['ID', 'Label']]

final_predictions.to_csv('xgboost_predictions.csv', index=False)

In [ ]:
from google.colab import files
files.download('xgboost_predictions.csv')

# Modeling with RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    class_weight='balanced'
)

In [ ]:
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

Accuracy: 0.9484649122807017
Confusion Matrix:
 [[5911  123]
 [ 206  144]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.98      0.97      6034
           1       0.54      0.41      0.47       350

    accuracy                           0.95      6384
   macro avg       0.75      0.70      0.72      6384
weighted avg       0.94      0.95      0.95      6384

In [ ]:
#Let's try param tuning

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

# Define a distribution of hyperparameters
param_dist = {
    'n_estimators': randint(100, 300),
    'max_depth': [None, 10, 20, 30, 50],
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5),
    'class_weight': ['balanced']
}

In [ ]:
rf = RandomForestClassifier(random_state=42)

random_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=20,
    scoring='f1',
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

print("✅ Best Params:", random_search.best_params_)

best_rf = random_search.best_estimator_

Fitting 5 folds for each of 20 candidates, totalling 100 fits
✅ Best Params: {'class_weight': 'balanced', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 101}

In [ ]:
#Training with best rf params

y_pred_rf = best_rf.predict(X_test)

print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

# Let's try Catboost classifier - apparently good with categorical data

In [ ]:
!pip install catboost

Collecting catboost
  Using cached catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost) (9.1.2)
Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 7.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [ ]:
from catboost import CatBoostClassifier

cat_cols = X_train.select_dtypes(include='object').columns.tolist()
cat_indices = [X_train.columns.get_loc(col) for col in cat_cols]

In [ ]:
cat_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    eval_metric='F1',
    random_state=42,
    verbose=100,
    auto_class_weights='Balanced'
)

In [ ]:
cat_model.fit(X_train, y_train, cat_features=cat_indices)

y_pred_cat = cat_model.predict(X_test)

print(confusion_matrix(y_test, y_pred_cat))
print(classification_report(y_test, y_pred_cat))

0:	learn: 0.9600408	total: 12.8ms	remaining: 12.8s
100:	learn: 0.9728672	total: 1.07s	remaining: 9.54s
200:	learn: 0.9768013	total: 2.11s	remaining: 8.38s
300:	learn: 0.9790322	total: 3.13s	remaining: 7.28s
400:	learn: 0.9806196	total: 5s	remaining: 7.47s
500:	learn: 0.9824052	total: 7.01s	remaining: 6.98s
600:	learn: 0.9839552	total: 8.07s	remaining: 5.36s
700:	learn: 0.9853889	total: 9.12s	remaining: 3.89s
800:	learn: 0.9868064	total: 10.2s	remaining: 2.54s
900:	learn: 0.9882077	total: 11.3s	remaining: 1.24s
999:	learn: 0.9894906	total: 12.3s	remaining: 0us
[[5741  293]
 [  27  323]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97      6034
           1       0.52      0.92      0.67       350

    accuracy                           0.95      6384
   macro avg       0.76      0.94      0.82      6384
weighted avg       0.97      0.95      0.96      6384

In [ ]:
cat_model = CatBoostClassifier(verbose=0)

grid = {
    'depth': [4, 6, 8],
    'learning_rate': [0.01, 0.1],
    'iterations': [100, 200],
}

grid_search = GridSearchCV(estimator=cat_model, param_grid=grid, cv=3, scoring='accuracy')
grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

Best Parameters: {'depth': 6, 'iterations': 100, 'learning_rate': 0.1}
Best Score: 0.9519110275689222

In [ ]:
# Extract best parameters
best_params = grid_search.best_params_

# Initialize and train final model
final_cat_model = CatBoostClassifier(**best_params, verbose=0)
final_cat_model.fit(X_train, y_train)

y_final_cat = final_cat_model.predict(X_test)

print(confusion_matrix(y_test, y_final_cat))
print(classification_report(y_test, y_final_cat))

[[5849  185]
 [ 125  225]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      6034
           1       0.55      0.64      0.59       350

    accuracy                           0.95      6384
   macro avg       0.76      0.81      0.78      6384
weighted avg       0.96      0.95      0.95      6384

In [ ]:
cat_test_data = test_data.copy()

predictions = final_cat_model.predict(cat_test_data)

# Add to test_data as 'label' column
cat_test_data['Label'] = predictions

In [ ]:
cat_results = cat_test_data[["ID", "Label"]]

In [ ]:
# Save predictions
cat_results.to_csv("cat_results.csv", index=False)

# Download the CSV
from google.colab import files
files.download("cat_results.csv")